---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: YAML Lint
        description: Run configurations on .yamllint file
        args:
          - '-c=.yamllint'
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v6.22.2
    hooks:
      - id: ansible-lint
        name: Ansible Lint
        description: Run configurations on .ansible-lint file
        args:
          - '-c=.ansible-lint'
