---
- name: Install jq if not present
  become: true
  ansible.builtin.yum:
    name:
      - jq
    state: present

- name: Execute health check script
#  become: true
  script: files/task.sh {{system_health_check_target}} {{system_health_check_wait}} {{system_health_check_status}} {{system_health_check_time}}