---
- name: Install git
  become: true
  ansible.builtin.yum:
      name:
        - git
      state: present

- name: Clone git project
  ansible.builtin.git:
    repo: "https://github.com/huyhoangit3/ansible-project.git"
    dest: "/home/vagrant/repo"
    clone: yes
    update: yes
  register: result_git_clone

- name: Print prev commit ID
  debug:
    msg:
      - "{{ result_git_clone.before }}"

- name: Print latest commit ID
  debug:
    msg:
      - "{{ result_git_clone.after }}"