---
- name: Install git
  become: true
  ansible.builtin.yum:
      name:
        - git
      state: present

- name: Clone git project
  ansible.builtin.git:
    repo: "{{git_clone_url}}"
    dest: "/home/vagrant/repo"
    clone: yes
    update: yes
    version: "{{ git_clone_hash if git_clone_hash is defined else 'master' }}"
  register: result_git_clone

- set_fact:
    git_clone_before_hash: "{{result_git_clone.before}}"
    git_clone_after_hash: "{{result_git_clone.after}}"

- name: Print before commit ID
  debug:
    msg:
      - "{{ git_clone_before_hash }}"

- name: Print after commit ID
  debug:
    msg:
      - "{{ git_clone_after_hash }}"