---
- name: Clone git project
  git:
    repo: https://github.com/huyhoangit3/ansible-project.git
    dest: /home/hoang
    clone: true
    update: true
  register: result_git_clone

- name: Print prev commit ID
  debug:
    msg:
      - "{{ result_git_clone.before }}"

- name: Print latest commit ID
  debug:
    msg:
      - "{{ result_git_clone.after }}"