---
- name: Get Service Status
  ansible.builtin.systemd:
    name: "{{radiusd_restart_check_service}}"
  register: service_status

- name: check stats_secondary_dns
  ansible.builtin.fail: msg="the service is not running"
  when: service_status.status.ActiveState != "running"
  ignore_errors: true