---

- name: Install nginx
  become: true
  ansible.builtin.yum:
    name:
      - nginx
    state: present

- name: Restart service nginx, in all cases
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: get service facts
  service_facts:
  register: services_state

- name: check if the nginx service is running
  ansible.builtin.fail:
    msg: the nginx service is not running
  when: services_state.ansible_facts.services["nginx.service"] is not defined