---

- name: Apply Template 1
  template:
    src: files/proxy.conf.realm.static.j2
    dest: /tmp/proxy.conf.realm.static

- name: Apply Template 2
  template:
    src: files/auth_edit_attribute.conf.j2
    dest: /tmp/auth_edit_attribute.conf